### ISSUE TITLE
Gvim

### ISSUE THREAD

**Issue by akemrir** [edkolev/tmuxline.vim#54]
Hi,

how can I disable tmuxline when launching gvim?
It messes up tmux appearance.

**Comment by ruiafonsopereira** [comment]
@akemrir, Since i suspect that you're not changing your statusline appearance on every Vim startup, I suggest you to use lazy loading to load the tmuxline.vim. For instance, if you are using [vim-plug](https://github.com/junegunn/vim-plug) is as easy as doing the following:
`Plug 'edkolev/tmuxline.vim', { 'on': [] }`
Then, when you want to interact with this plugin, just load it.

**Comment by akemrir** [comment]
I have own utility to install plugins for vim.
All plugins are loaded on start.

If its not possible with settings, maybe "if has('gui')" would be usable.
But I don't know what is used in plugin to load, to prevent it eventually.

**Comment by Brottweiler** [comment]
I just noticed that opening vim or gvim it resets tmuxline to default (airline) when I've already choosed and saved the theme powerline for tmuxline.

**Comment by Brottweiler** [comment]
@ruiafonsopereira How would this be done using [Vundle](https://github.com/VundleVim/Vundle.vim)?

Since opening vim every time messes up the colors and formatting in the tmuxline, if I comment out tmuxline in my vim config so it does not load, it does not mess up tmuxline. But then I've essentually removed tmuxline plugin.

Your suggestion for vim-plug does not seem to work for Vundle.

**Comment by ruiafonsopereira** [comment]
Hi @Brottweiler 

I have never used Vundle and thus I can't help you with that. I have came across the same problem and my working solution was shared on [my first comment](https://github.com/edkolev/tmuxline.vim/issues/54#issuecomment-208761160) on this issue.

> Since opening vim every time messes up the colors and formatting in the tmuxline, if I comment out tmuxline in my vim config so it does not load, it does not mess up tmuxline. But then I've essentually removed tmuxline plugin.

While trying to figure out a solution, I've also learnt this.

**Comment by Brottweiler** [comment]
@ruiafonsopereira It sounded like, for plug-vim, adding the `, { 'on': [] }` makes the plugin not be loaded until you manually load it, so in your case you would not have to comment out, or remove, the plugin. Right?

**Comment by ruiafonsopereira** [comment]
Exactly, @Brottweiler.

**Comment by akemrir** [comment]
Please glose this. It's old and not relevant anymore.
